INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 1, 'Quận Ba Đình', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 2, 'Quận Hoàn Kiếm', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 3, 'Quận Tây Hồ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 4, 'Quận Long Biên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 5, 'Quận Cầu Giấy', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 6, 'Quận Đống Đa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 7, 'Quận Hai Bà Trưng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 8, 'Quận Hoàng Mai', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 9, 'Quận Thanh Xuân', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 16, 'Huyện Sóc Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 17, 'Huyện Đông Anh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 18, 'Huyện Gia Lâm', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 19, 'Quận Nam Từ Liêm', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 20, 'Huyện Thanh Trì', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 21, 'Quận Bắc Từ Liêm', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (2, 24, 'Thành phố Hà Giang', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (2, 26, 'Huyện Đồng Văn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (2, 27, 'Huyện Mèo Vạc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (2, 28, 'Huyện Yên Minh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (2, 29, 'Huyện Quản Bạ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (2, 30, 'Huyện Vị Xuyên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (2, 31, 'Huyện Bắc Mê', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (2, 32, 'Huyện Hoàng Su Phì', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (2, 33, 'Huyện Xín Mần', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (2, 34, 'Huyện Bắc Quang', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (2, 35, 'Huyện Quang Bình', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (4, 40, 'Thành phố Cao Bằng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (4, 42, 'Huyện Bảo Lâm', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (4, 43, 'Huyện Bảo Lạc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (4, 45, 'Huyện Hà Quảng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (4, 47, 'Huyện Trùng Khánh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (4, 48, 'Huyện Hạ Lang', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (4, 49, 'Huyện Quảng Hòa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (4, 51, 'Huyện Hoà An', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (4, 52, 'Huyện Nguyên Bình', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (4, 53, 'Huyện Thạch An', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (6, 58, 'Thành Phố Bắc Kạn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (6, 60, 'Huyện Pác Nặm', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (6, 61, 'Huyện Ba Bể', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (6, 62, 'Huyện Ngân Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (6, 63, 'Huyện Bạch Thông', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (6, 64, 'Huyện Chợ Đồn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (6, 65, 'Huyện Chợ Mới', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (6, 66, 'Huyện Na Rì', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (8, 70, 'Thành phố Tuyên Quang', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (8, 71, 'Huyện Lâm Bình', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (8, 72, 'Huyện Na Hang', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (8, 73, 'Huyện Chiêm Hóa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (8, 74, 'Huyện Hàm Yên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (8, 75, 'Huyện Yên Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (8, 76, 'Huyện Sơn Dương', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (10, 80, 'Thành phố Lào Cai', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (10, 82, 'Huyện Bát Xát', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (10, 83, 'Huyện Mường Khương', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (10, 84, 'Huyện Si Ma Cai', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (10, 85, 'Huyện Bắc Hà', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (10, 86, 'Huyện Bảo Thắng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (10, 87, 'Huyện Bảo Yên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (10, 88, 'Thị xã Sa Pa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (10, 89, 'Huyện Văn Bàn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (11, 94, 'Thành phố Điện Biên Phủ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (11, 95, 'Thị Xã Mường Lay', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (11, 96, 'Huyện Mường Nhé', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (11, 97, 'Huyện Mường Chà', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (11, 98, 'Huyện Tủa Chùa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (11, 99, 'Huyện Tuần Giáo', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (11, 100, 'Huyện Điện Biên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (11, 101, 'Huyện Điện Biên Đông', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (11, 102, 'Huyện Mường Ảng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (11, 103, 'Huyện Nậm Pồ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (12, 105, 'Thành phố Lai Châu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (12, 106, 'Huyện Tam Đường', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (12, 107, 'Huyện Mường Tè', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (12, 108, 'Huyện Sìn Hồ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (12, 109, 'Huyện Phong Thổ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (12, 110, 'Huyện Than Uyên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (12, 111, 'Huyện Tân Uyên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (12, 112, 'Huyện Nậm Nhùn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (14, 116, 'Thành phố Sơn La', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (14, 118, 'Huyện Quỳnh Nhai', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (14, 119, 'Huyện Thuận Châu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (14, 120, 'Huyện Mường La', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (14, 121, 'Huyện Bắc Yên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (14, 122, 'Huyện Phù Yên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (14, 123, 'Huyện Mộc Châu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (14, 124, 'Huyện Yên Châu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (14, 125, 'Huyện Mai Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (14, 126, 'Huyện Sông Mã', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (14, 127, 'Huyện Sốp Cộp', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (14, 128, 'Huyện Vân Hồ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (15, 132, 'Thành phố Yên Bái', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (15, 133, 'Thị xã Nghĩa Lộ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (15, 135, 'Huyện Lục Yên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (15, 136, 'Huyện Văn Yên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (15, 137, 'Huyện Mù Căng Chải', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (15, 138, 'Huyện Trấn Yên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (15, 139, 'Huyện Trạm Tấu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (15, 140, 'Huyện Văn Chấn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (15, 141, 'Huyện Yên Bình', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (17, 148, 'Thành phố Hòa Bình', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (17, 150, 'Huyện Đà Bắc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (17, 152, 'Huyện Lương Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (17, 153, 'Huyện Kim Bôi', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (17, 154, 'Huyện Cao Phong', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (17, 155, 'Huyện Tân Lạc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (17, 156, 'Huyện Mai Châu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (17, 157, 'Huyện Lạc Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (17, 158, 'Huyện Yên Thủy', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (17, 159, 'Huyện Lạc Thủy', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (19, 164, 'Thành phố Thái Nguyên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (19, 165, 'Thành phố Sông Công', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (19, 167, 'Huyện Định Hóa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (19, 168, 'Huyện Phú Lương', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (19, 169, 'Huyện Đồng Hỷ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (19, 170, 'Huyện Võ Nhai', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (19, 171, 'Huyện Đại Từ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (19, 172, 'Thành phố Phổ Yên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (19, 173, 'Huyện Phú Bình', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (20, 178, 'Thành phố Lạng Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (20, 180, 'Huyện Tràng Định', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (20, 181, 'Huyện Bình Gia', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (20, 182, 'Huyện Văn Lãng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (20, 183, 'Huyện Cao Lộc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (20, 184, 'Huyện Văn Quan', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (20, 185, 'Huyện Bắc Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (20, 186, 'Huyện Hữu Lũng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (20, 187, 'Huyện Chi Lăng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (20, 188, 'Huyện Lộc Bình', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (20, 189, 'Huyện Đình Lập', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (22, 193, 'Thành phố Hạ Long', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (22, 194, 'Thành phố Móng Cái', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (22, 195, 'Thành phố Cẩm Phả', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (22, 196, 'Thành phố Uông Bí', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (22, 198, 'Huyện Bình Liêu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (22, 199, 'Huyện Tiên Yên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (22, 200, 'Huyện Đầm Hà', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (22, 201, 'Huyện Hải Hà', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (22, 202, 'Huyện Ba Chẽ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (22, 203, 'Huyện Vân Đồn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (22, 205, 'Thị xã Đông Triều', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (22, 206, 'Thị xã Quảng Yên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (22, 207, 'Huyện Cô Tô', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (24, 213, 'Thành phố Bắc Giang', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (24, 215, 'Huyện Yên Thế', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (24, 216, 'Huyện Tân Yên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (24, 217, 'Huyện Lạng Giang', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (24, 218, 'Huyện Lục Nam', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (24, 219, 'Huyện Lục Ngạn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (24, 220, 'Huyện Sơn Động', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (24, 221, 'Huyện Yên Dũng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (24, 222, 'Huyện Việt Yên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (24, 223, 'Huyện Hiệp Hòa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (25, 227, 'Thành phố Việt Trì', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (25, 228, 'Thị xã Phú Thọ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (25, 230, 'Huyện Đoan Hùng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (25, 231, 'Huyện Hạ Hoà', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (25, 232, 'Huyện Thanh Ba', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (25, 233, 'Huyện Phù Ninh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (25, 234, 'Huyện Yên Lập', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (25, 235, 'Huyện Cẩm Khê', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (25, 236, 'Huyện Tam Nông', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (25, 237, 'Huyện Lâm Thao', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (25, 238, 'Huyện Thanh Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (25, 239, 'Huyện Thanh Thuỷ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (25, 240, 'Huyện Tân Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (26, 243, 'Thành phố Vĩnh Yên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (26, 244, 'Thành phố Phúc Yên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (26, 246, 'Huyện Lập Thạch', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (26, 247, 'Huyện Tam Dương', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (26, 248, 'Huyện Tam Đảo', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (26, 249, 'Huyện Bình Xuyên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 250, 'Huyện Mê Linh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (26, 251, 'Huyện Yên Lạc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (26, 252, 'Huyện Vĩnh Tường', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (26, 253, 'Huyện Sông Lô', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (27, 256, 'Thành phố Bắc Ninh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (27, 258, 'Huyện Yên Phong', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (27, 259, 'Huyện Quế Võ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (27, 260, 'Huyện Tiên Du', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (27, 261, 'Thành phố Từ Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (27, 262, 'Huyện Thuận Thành', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (27, 263, 'Huyện Gia Bình', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (27, 264, 'Huyện Lương Tài', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 268, 'Quận Hà Đông', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 269, 'Thị xã Sơn Tây', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 271, 'Huyện Ba Vì', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 272, 'Huyện Phúc Thọ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 273, 'Huyện Đan Phượng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 274, 'Huyện Hoài Đức', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 275, 'Huyện Quốc Oai', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 276, 'Huyện Thạch Thất', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 277, 'Huyện Chương Mỹ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 278, 'Huyện Thanh Oai', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 279, 'Huyện Thường Tín', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 280, 'Huyện Phú Xuyên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 281, 'Huyện Ứng Hòa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (1, 282, 'Huyện Mỹ Đức', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (30, 288, 'Thành phố Hải Dương', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (30, 290, 'Thành phố Chí Linh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (30, 291, 'Huyện Nam Sách', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (30, 292, 'Thị xã Kinh Môn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (30, 293, 'Huyện Kim Thành', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (30, 294, 'Huyện Thanh Hà', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (30, 295, 'Huyện Cẩm Giàng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (30, 296, 'Huyện Bình Giang', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (30, 297, 'Huyện Gia Lộc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (30, 298, 'Huyện Tứ Kỳ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (30, 299, 'Huyện Ninh Giang', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (30, 300, 'Huyện Thanh Miện', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (31, 303, 'Quận Hồng Bàng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (31, 304, 'Quận Ngô Quyền', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (31, 305, 'Quận Lê Chân', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (31, 306, 'Quận Hải An', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (31, 307, 'Quận Kiến An', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (31, 308, 'Quận Đồ Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (31, 309, 'Quận Dương Kinh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (31, 311, 'Huyện Thuỷ Nguyên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (31, 312, 'Huyện An Dương', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (31, 313, 'Huyện An Lão', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (31, 314, 'Huyện Kiến Thuỵ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (31, 315, 'Huyện Tiên Lãng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (31, 316, 'Huyện Vĩnh Bảo', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (31, 317, 'Huyện Cát Hải', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (31, 318, 'Huyện Bạch Long Vĩ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (33, 323, 'Thành phố Hưng Yên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (33, 325, 'Huyện Văn Lâm', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (33, 326, 'Huyện Văn Giang', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (33, 327, 'Huyện Yên Mỹ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (33, 328, 'Thị xã Mỹ Hào', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (33, 329, 'Huyện Ân Thi', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (33, 330, 'Huyện Khoái Châu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (33, 331, 'Huyện Kim Động', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (33, 332, 'Huyện Tiên Lữ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (33, 333, 'Huyện Phù Cừ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (34, 336, 'Thành phố Thái Bình', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (34, 338, 'Huyện Quỳnh Phụ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (34, 339, 'Huyện Hưng Hà', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (34, 340, 'Huyện Đông Hưng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (34, 341, 'Huyện Thái Thụy', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (34, 342, 'Huyện Tiền Hải', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (34, 343, 'Huyện Kiến Xương', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (34, 344, 'Huyện Vũ Thư', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (35, 347, 'Thành phố Phủ Lý', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (35, 349, 'Thị xã Duy Tiên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (35, 350, 'Huyện Kim Bảng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (35, 351, 'Huyện Thanh Liêm', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (35, 352, 'Huyện Bình Lục', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (35, 353, 'Huyện Lý Nhân', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (36, 356, 'Thành phố Nam Định', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (36, 358, 'Huyện Mỹ Lộc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (36, 359, 'Huyện Vụ Bản', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (36, 360, 'Huyện Ý Yên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (36, 361, 'Huyện Nghĩa Hưng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (36, 362, 'Huyện Nam Trực', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (36, 363, 'Huyện Trực Ninh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (36, 364, 'Huyện Xuân Trường', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (36, 365, 'Huyện Giao Thủy', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (36, 366, 'Huyện Hải Hậu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (37, 369, 'Thành phố Ninh Bình', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (37, 370, 'Thành phố Tam Điệp', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (37, 372, 'Huyện Nho Quan', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (37, 373, 'Huyện Gia Viễn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (37, 374, 'Huyện Hoa Lư', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (37, 375, 'Huyện Yên Khánh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (37, 376, 'Huyện Kim Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (37, 377, 'Huyện Yên Mô', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 380, 'Thành phố Thanh Hóa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 381, 'Thị xã Bỉm Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 382, 'Thành phố Sầm Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 384, 'Huyện Mường Lát', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 385, 'Huyện Quan Hóa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 386, 'Huyện Bá Thước', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 387, 'Huyện Quan Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 388, 'Huyện Lang Chánh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 389, 'Huyện Ngọc Lặc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 390, 'Huyện Cẩm Thủy', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 391, 'Huyện Thạch Thành', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 392, 'Huyện Hà Trung', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 393, 'Huyện Vĩnh Lộc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 394, 'Huyện Yên Định', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 395, 'Huyện Thọ Xuân', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 396, 'Huyện Thường Xuân', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 397, 'Huyện Triệu Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 398, 'Huyện Thiệu Hóa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 399, 'Huyện Hoằng Hóa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 400, 'Huyện Hậu Lộc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 401, 'Huyện Nga Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 402, 'Huyện Như Xuân', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 403, 'Huyện Như Thanh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 404, 'Huyện Nông Cống', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 405, 'Huyện Đông Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 406, 'Huyện Quảng Xương', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (38, 407, 'Thị xã Nghi Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (40, 412, 'Thành phố Vinh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (40, 413, 'Thị xã Cửa Lò', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (40, 414, 'Thị xã Thái Hoà', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (40, 415, 'Huyện Quế Phong', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (40, 416, 'Huyện Quỳ Châu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (40, 417, 'Huyện Kỳ Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (40, 418, 'Huyện Tương Dương', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (40, 419, 'Huyện Nghĩa Đàn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (40, 420, 'Huyện Quỳ Hợp', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (40, 421, 'Huyện Quỳnh Lưu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (40, 422, 'Huyện Con Cuông', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (40, 423, 'Huyện Tân Kỳ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (40, 424, 'Huyện Anh Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (40, 425, 'Huyện Diễn Châu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (40, 426, 'Huyện Yên Thành', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (40, 427, 'Huyện Đô Lương', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (40, 428, 'Huyện Thanh Chương', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (40, 429, 'Huyện Nghi Lộc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (40, 430, 'Huyện Nam Đàn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (40, 431, 'Huyện Hưng Nguyên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (40, 432, 'Thị xã Hoàng Mai', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (42, 436, 'Thành phố Hà Tĩnh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (42, 437, 'Thị xã Hồng Lĩnh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (42, 439, 'Huyện Hương Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (42, 440, 'Huyện Đức Thọ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (42, 441, 'Huyện Vũ Quang', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (42, 442, 'Huyện Nghi Xuân', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (42, 443, 'Huyện Can Lộc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (42, 444, 'Huyện Hương Khê', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (42, 445, 'Huyện Thạch Hà', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (42, 446, 'Huyện Cẩm Xuyên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (42, 447, 'Huyện Kỳ Anh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (42, 448, 'Huyện Lộc Hà', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (42, 449, 'Thị xã Kỳ Anh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (44, 450, 'Thành Phố Đồng Hới', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (44, 452, 'Huyện Minh Hóa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (44, 453, 'Huyện Tuyên Hóa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (44, 454, 'Huyện Quảng Trạch', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (44, 455, 'Huyện Bố Trạch', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (44, 456, 'Huyện Quảng Ninh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (44, 457, 'Huyện Lệ Thủy', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (44, 458, 'Thị xã Ba Đồn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (45, 461, 'Thành phố Đông Hà', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (45, 462, 'Thị xã Quảng Trị', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (45, 464, 'Huyện Vĩnh Linh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (45, 465, 'Huyện Hướng Hóa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (45, 466, 'Huyện Gio Linh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (45, 467, 'Huyện Đa Krông', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (45, 468, 'Huyện Cam Lộ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (45, 469, 'Huyện Triệu Phong', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (45, 470, 'Huyện Hải Lăng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (45, 471, 'Huyện Cồn Cỏ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (46, 474, 'Thành phố Huế', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (46, 476, 'Huyện Phong Điền', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (46, 477, 'Huyện Quảng Điền', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (46, 478, 'Huyện Phú Vang', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (46, 479, 'Thị xã Hương Thủy', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (46, 480, 'Thị xã Hương Trà', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (46, 481, 'Huyện A Lưới', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (46, 482, 'Huyện Phú Lộc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (46, 483, 'Huyện Nam Đông', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (48, 490, 'Quận Liên Chiểu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (48, 491, 'Quận Thanh Khê', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (48, 492, 'Quận Hải Châu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (48, 493, 'Quận Sơn Trà', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (48, 494, 'Quận Ngũ Hành Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (48, 495, 'Quận Cẩm Lệ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (48, 497, 'Huyện Hòa Vang', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (48, 498, 'Huyện Hoàng Sa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (49, 502, 'Thành phố Tam Kỳ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (49, 503, 'Thành phố Hội An', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (49, 504, 'Huyện Tây Giang', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (49, 505, 'Huyện Đông Giang', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (49, 506, 'Huyện Đại Lộc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (49, 507, 'Thị xã Điện Bàn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (49, 508, 'Huyện Duy Xuyên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (49, 509, 'Huyện Quế Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (49, 510, 'Huyện Nam Giang', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (49, 511, 'Huyện Phước Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (49, 512, 'Huyện Hiệp Đức', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (49, 513, 'Huyện Thăng Bình', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (49, 514, 'Huyện Tiên Phước', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (49, 515, 'Huyện Bắc Trà My', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (49, 516, 'Huyện Nam Trà My', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (49, 517, 'Huyện Núi Thành', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (49, 518, 'Huyện Phú Ninh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (49, 519, 'Huyện Nông Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (51, 522, 'Thành phố Quảng Ngãi', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (51, 524, 'Huyện Bình Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (51, 525, 'Huyện Trà Bồng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (51, 527, 'Huyện Sơn Tịnh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (51, 528, 'Huyện Tư Nghĩa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (51, 529, 'Huyện Sơn Hà', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (51, 530, 'Huyện Sơn Tây', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (51, 531, 'Huyện Minh Long', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (51, 532, 'Huyện Nghĩa Hành', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (51, 533, 'Huyện Mộ Đức', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (51, 534, 'Thị xã Đức Phổ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (51, 535, 'Huyện Ba Tơ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (51, 536, 'Huyện Lý Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (52, 540, 'Thành phố Quy Nhơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (52, 542, 'Huyện An Lão', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (52, 543, 'Thị xã Hoài Nhơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (52, 544, 'Huyện Hoài Ân', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (52, 545, 'Huyện Phù Mỹ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (52, 546, 'Huyện Vĩnh Thạnh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (52, 547, 'Huyện Tây Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (52, 548, 'Huyện Phù Cát', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (52, 549, 'Thị xã An Nhơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (52, 550, 'Huyện Tuy Phước', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (52, 551, 'Huyện Vân Canh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (54, 555, 'Thành phố Tuy Hoà', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (54, 557, 'Thị xã Sông Cầu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (54, 558, 'Huyện Đồng Xuân', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (54, 559, 'Huyện Tuy An', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (54, 560, 'Huyện Sơn Hòa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (54, 561, 'Huyện Sông Hinh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (54, 562, 'Huyện Tây Hoà', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (54, 563, 'Huyện Phú Hoà', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (54, 564, 'Thị xã Đông Hòa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (56, 568, 'Thành phố Nha Trang', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (56, 569, 'Thành phố Cam Ranh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (56, 570, 'Huyện Cam Lâm', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (56, 571, 'Huyện Vạn Ninh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (56, 572, 'Thị xã Ninh Hòa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (56, 573, 'Huyện Khánh Vĩnh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (56, 574, 'Huyện Diên Khánh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (56, 575, 'Huyện Khánh Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (56, 576, 'Huyện Trường Sa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (58, 582, 'Thành phố Phan Rang-Tháp Chàm', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (58, 584, 'Huyện Bác Ái', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (58, 585, 'Huyện Ninh Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (58, 586, 'Huyện Ninh Hải', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (58, 587, 'Huyện Ninh Phước', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (58, 588, 'Huyện Thuận Bắc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (58, 589, 'Huyện Thuận Nam', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (60, 593, 'Thành phố Phan Thiết', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (60, 594, 'Thị xã La Gi', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (60, 595, 'Huyện Tuy Phong', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (60, 596, 'Huyện Bắc Bình', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (60, 597, 'Huyện Hàm Thuận Bắc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (60, 598, 'Huyện Hàm Thuận Nam', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (60, 599, 'Huyện Tánh Linh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (60, 600, 'Huyện Đức Linh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (60, 601, 'Huyện Hàm Tân', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (60, 602, 'Huyện Phú Quí', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (62, 608, 'Thành phố Kon Tum', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (62, 610, 'Huyện Đắk Glei', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (62, 611, 'Huyện Ngọc Hồi', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (62, 612, 'Huyện Đắk Tô', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (62, 613, 'Huyện Kon Plông', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (62, 614, 'Huyện Kon Rẫy', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (62, 615, 'Huyện Đắk Hà', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (62, 616, 'Huyện Sa Thầy', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (62, 617, 'Huyện Tu Mơ Rông', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (62, 618, 'Huyện Ia H\' Drai', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (64, 622, 'Thành phố Pleiku', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (64, 623, 'Thị xã An Khê', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (64, 624, 'Thị xã Ayun Pa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (64, 625, 'Huyện KBang', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (64, 626, 'Huyện Đăk Đoa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (64, 627, 'Huyện Chư Păh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (64, 628, 'Huyện Ia Grai', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (64, 629, 'Huyện Mang Yang', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (64, 630, 'Huyện Kông Chro', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (64, 631, 'Huyện Đức Cơ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (64, 632, 'Huyện Chư Prông', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (64, 633, 'Huyện Chư Sê', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (64, 634, 'Huyện Đăk Pơ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (64, 635, 'Huyện Ia Pa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (64, 637, 'Huyện Krông Pa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (64, 638, 'Huyện Phú Thiện', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (64, 639, 'Huyện Chư Pưh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (66, 643, 'Thành phố Buôn Ma Thuột', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (66, 644, 'Thị Xã Buôn Hồ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (66, 645, 'Huyện Ea H\'leo', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (66, 646, 'Huyện Ea Súp', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (66, 647, 'Huyện Buôn Đôn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (66, 648, 'Huyện Cư M\'gar', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (66, 649, 'Huyện Krông Búk', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (66, 650, 'Huyện Krông Năng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (66, 651, 'Huyện Ea Kar', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (66, 652, 'Huyện M\'Đrắk', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (66, 653, 'Huyện Krông Bông', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (66, 654, 'Huyện Krông Pắc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (66, 655, 'Huyện Krông A Na', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (66, 656, 'Huyện Lắk', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (66, 657, 'Huyện Cư Kuin', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (67, 660, 'Thành phố Gia Nghĩa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (67, 661, 'Huyện Đăk Glong', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (67, 662, 'Huyện Cư Jút', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (67, 663, 'Huyện Đắk Mil', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (67, 664, 'Huyện Krông Nô', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (67, 665, 'Huyện Đắk Song', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (67, 666, 'Huyện Đắk R\'Lấp', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (67, 667, 'Huyện Tuy Đức', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (68, 672, 'Thành phố Đà Lạt', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (68, 673, 'Thành phố Bảo Lộc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (68, 674, 'Huyện Đam Rông', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (68, 675, 'Huyện Lạc Dương', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (68, 676, 'Huyện Lâm Hà', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (68, 677, 'Huyện Đơn Dương', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (68, 678, 'Huyện Đức Trọng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (68, 679, 'Huyện Di Linh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (68, 680, 'Huyện Bảo Lâm', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (68, 681, 'Huyện Đạ Huoai', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (68, 682, 'Huyện Đạ Tẻh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (68, 683, 'Huyện Cát Tiên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (70, 688, 'Thị xã Phước Long', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (70, 689, 'Thành phố Đồng Xoài', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (70, 690, 'Thị xã Bình Long', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (70, 691, 'Huyện Bù Gia Mập', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (70, 692, 'Huyện Lộc Ninh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (70, 693, 'Huyện Bù Đốp', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (70, 694, 'Huyện Hớn Quản', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (70, 695, 'Huyện Đồng Phú', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (70, 696, 'Huyện Bù Đăng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (70, 697, 'Thị xã Chơn Thành', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (70, 698, 'Huyện Phú Riềng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (72, 703, 'Thành phố Tây Ninh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (72, 705, 'Huyện Tân Biên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (72, 706, 'Huyện Tân Châu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (72, 707, 'Huyện Dương Minh Châu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (72, 708, 'Huyện Châu Thành', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (72, 709, 'Thị xã Hòa Thành', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (72, 710, 'Huyện Gò Dầu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (72, 711, 'Huyện Bến Cầu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (72, 712, 'Thị xã Trảng Bàng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (74, 718, 'Thành phố Thủ Dầu Một', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (74, 719, 'Huyện Bàu Bàng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (74, 720, 'Huyện Dầu Tiếng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (74, 721, 'Thị xã Bến Cát', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (74, 722, 'Huyện Phú Giáo', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (74, 723, 'Thị xã Tân Uyên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (74, 724, 'Thành phố Dĩ An', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (74, 725, 'Thành phố Thuận An', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (74, 726, 'Huyện Bắc Tân Uyên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (75, 731, 'Thành phố Biên Hòa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (75, 732, 'Thành phố Long Khánh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (75, 734, 'Huyện Tân Phú', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (75, 735, 'Huyện Vĩnh Cửu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (75, 736, 'Huyện Định Quán', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (75, 737, 'Huyện Trảng Bom', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (75, 738, 'Huyện Thống Nhất', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (75, 739, 'Huyện Cẩm Mỹ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (75, 740, 'Huyện Long Thành', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (75, 741, 'Huyện Xuân Lộc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (75, 742, 'Huyện Nhơn Trạch', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (77, 747, 'Thành phố Vũng Tàu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (77, 748, 'Thành phố Bà Rịa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (77, 750, 'Huyện Châu Đức', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (77, 751, 'Huyện Xuyên Mộc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (77, 752, 'Huyện Long Điền', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (77, 753, 'Huyện Đất Đỏ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (77, 754, 'Thị xã Phú Mỹ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (77, 755, 'Huyện Côn Đảo', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 760, 'Quận 1', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 761, 'Quận 12', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 764, 'Quận Gò Vấp', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 765, 'Quận Bình Thạnh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 766, 'Quận Tân Bình', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 767, 'Quận Tân Phú', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 768, 'Quận Phú Nhuận', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 769, 'Thành phố Thủ Đức', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 770, 'Quận 3', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 771, 'Quận 10', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 772, 'Quận 11', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 773, 'Quận 4', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 774, 'Quận 5', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 775, 'Quận 6', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 776, 'Quận 8', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 777, 'Quận Bình Tân', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 778, 'Quận 7', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 783, 'Huyện Củ Chi', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 784, 'Huyện Hóc Môn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 785, 'Huyện Bình Chánh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 786, 'Huyện Nhà Bè', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (79, 787, 'Huyện Cần Giờ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (80, 794, 'Thành phố Tân An', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (80, 795, 'Thị xã Kiến Tường', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (80, 796, 'Huyện Tân Hưng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (80, 797, 'Huyện Vĩnh Hưng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (80, 798, 'Huyện Mộc Hóa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (80, 799, 'Huyện Tân Thạnh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (80, 800, 'Huyện Thạnh Hóa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (80, 801, 'Huyện Đức Huệ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (80, 802, 'Huyện Đức Hòa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (80, 803, 'Huyện Bến Lức', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (80, 804, 'Huyện Thủ Thừa', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (80, 805, 'Huyện Tân Trụ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (80, 806, 'Huyện Cần Đước', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (80, 807, 'Huyện Cần Giuộc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (80, 808, 'Huyện Châu Thành', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (82, 815, 'Thành phố Mỹ Tho', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (82, 816, 'Thị xã Gò Công', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (82, 817, 'Thị xã Cai Lậy', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (82, 818, 'Huyện Tân Phước', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (82, 819, 'Huyện Cái Bè', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (82, 820, 'Huyện Cai Lậy', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (82, 821, 'Huyện Châu Thành', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (82, 822, 'Huyện Chợ Gạo', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (82, 823, 'Huyện Gò Công Tây', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (82, 824, 'Huyện Gò Công Đông', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (82, 825, 'Huyện Tân Phú Đông', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (83, 829, 'Thành phố Bến Tre', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (83, 831, 'Huyện Châu Thành', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (83, 832, 'Huyện Chợ Lách', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (83, 833, 'Huyện Mỏ Cày Nam', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (83, 834, 'Huyện Giồng Trôm', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (83, 835, 'Huyện Bình Đại', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (83, 836, 'Huyện Ba Tri', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (83, 837, 'Huyện Thạnh Phú', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (83, 838, 'Huyện Mỏ Cày Bắc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (84, 842, 'Thành phố Trà Vinh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (84, 844, 'Huyện Càng Long', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (84, 845, 'Huyện Cầu Kè', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (84, 846, 'Huyện Tiểu Cần', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (84, 847, 'Huyện Châu Thành', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (84, 848, 'Huyện Cầu Ngang', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (84, 849, 'Huyện Trà Cú', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (84, 850, 'Huyện Duyên Hải', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (84, 851, 'Thị xã Duyên Hải', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (86, 855, 'Thành phố Vĩnh Long', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (86, 857, 'Huyện Long Hồ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (86, 858, 'Huyện Mang Thít', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (86, 859, 'Huyện  Vũng Liêm', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (86, 860, 'Huyện Tam Bình', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (86, 861, 'Thị xã Bình Minh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (86, 862, 'Huyện Trà Ôn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (86, 863, 'Huyện Bình Tân', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (87, 866, 'Thành phố Cao Lãnh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (87, 867, 'Thành phố Sa Đéc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (87, 868, 'Thành phố Hồng Ngự', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (87, 869, 'Huyện Tân Hồng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (87, 870, 'Huyện Hồng Ngự', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (87, 871, 'Huyện Tam Nông', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (87, 872, 'Huyện Tháp Mười', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (87, 873, 'Huyện Cao Lãnh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (87, 874, 'Huyện Thanh Bình', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (87, 875, 'Huyện Lấp Vò', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (87, 876, 'Huyện Lai Vung', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (87, 877, 'Huyện Châu Thành', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (89, 883, 'Thành phố Long Xuyên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (89, 884, 'Thành phố Châu Đốc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (89, 886, 'Huyện An Phú', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (89, 887, 'Thị xã Tân Châu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (89, 888, 'Huyện Phú Tân', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (89, 889, 'Huyện Châu Phú', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (89, 890, 'Huyện Tịnh Biên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (89, 891, 'Huyện Tri Tôn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (89, 892, 'Huyện Châu Thành', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (89, 893, 'Huyện Chợ Mới', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (89, 894, 'Huyện Thoại Sơn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (91, 899, 'Thành phố Rạch Giá', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (91, 900, 'Thành phố Hà Tiên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (91, 902, 'Huyện Kiên Lương', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (91, 903, 'Huyện Hòn Đất', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (91, 904, 'Huyện Tân Hiệp', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (91, 905, 'Huyện Châu Thành', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (91, 906, 'Huyện Giồng Riềng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (91, 907, 'Huyện Gò Quao', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (91, 908, 'Huyện An Biên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (91, 909, 'Huyện An Minh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (91, 910, 'Huyện Vĩnh Thuận', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (91, 911, 'Thành phố Phú Quốc', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (91, 912, 'Huyện Kiên Hải', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (91, 913, 'Huyện U Minh Thượng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (91, 914, 'Huyện Giang Thành', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (92, 916, 'Quận Ninh Kiều', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (92, 917, 'Quận Ô Môn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (92, 918, 'Quận Bình Thuỷ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (92, 919, 'Quận Cái Răng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (92, 923, 'Quận Thốt Nốt', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (92, 924, 'Huyện Vĩnh Thạnh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (92, 925, 'Huyện Cờ Đỏ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (92, 926, 'Huyện Phong Điền', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (92, 927, 'Huyện Thới Lai', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (93, 930, 'Thành phố Vị Thanh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (93, 931, 'Thành phố Ngã Bảy', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (93, 932, 'Huyện Châu Thành A', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (93, 933, 'Huyện Châu Thành', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (93, 934, 'Huyện Phụng Hiệp', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (93, 935, 'Huyện Vị Thuỷ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (93, 936, 'Huyện Long Mỹ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (93, 937, 'Thị xã Long Mỹ', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (94, 941, 'Thành phố Sóc Trăng', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (94, 942, 'Huyện Châu Thành', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (94, 943, 'Huyện Kế Sách', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (94, 944, 'Huyện Mỹ Tú', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (94, 945, 'Huyện Cù Lao Dung', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (94, 946, 'Huyện Long Phú', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (94, 947, 'Huyện Mỹ Xuyên', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (94, 948, 'Thị xã Ngã Năm', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (94, 949, 'Huyện Thạnh Trị', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (94, 950, 'Thị xã Vĩnh Châu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (94, 951, 'Huyện Trần Đề', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (95, 954, 'Thành phố Bạc Liêu', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (95, 956, 'Huyện Hồng Dân', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (95, 957, 'Huyện Phước Long', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (95, 958, 'Huyện Vĩnh Lợi', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (95, 959, 'Thị xã Giá Rai', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (95, 960, 'Huyện Đông Hải', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (95, 961, 'Huyện Hoà Bình', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (96, 964, 'Thành phố Cà Mau', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (96, 966, 'Huyện U Minh', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (96, 967, 'Huyện Thới Bình', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (96, 968, 'Huyện Trần Văn Thời', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (96, 969, 'Huyện Cái Nước', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (96, 970, 'Huyện Đầm Dơi', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (96, 971, 'Huyện Năm Căn', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (96, 972, 'Huyện Phú Tân', NULL);
INSERT INTO `district` (`id_province`, `id_district`, `str_district`, `id_status`) VALUES (96, 973, 'Huyện Ngọc Hiển', NULL);
