INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (1, 'Thành phố Hà Nội', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (2, 'Tỉnh Hà Giang', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (4, 'Tỉnh Cao Bằng', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (6, 'Tỉnh Bắc Kạn', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (8, 'Tỉnh Tuyên Quang', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (10, 'Tỉnh Lào Cai', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (11, 'Tỉnh Điện Biên', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (12, 'Tỉnh Lai Châu', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (14, 'Tỉnh Sơn La', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (15, 'Tỉnh Yên Bái', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (17, 'Tỉnh Hoà Bình', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (19, 'Tỉnh Thái Nguyên', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (20, 'Tỉnh Lạng Sơn', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (22, 'Tỉnh Quảng Ninh', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (24, 'Tỉnh Bắc Giang', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (25, 'Tỉnh Phú Thọ', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (26, 'Tỉnh Vĩnh Phúc', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (27, 'Tỉnh Bắc Ninh', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (30, 'Tỉnh Hải Dương', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (31, 'Thành phố Hải Phòng', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (33, 'Tỉnh Hưng Yên', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (34, 'Tỉnh Thái Bình', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (35, 'Tỉnh Hà Nam', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (36, 'Tỉnh Nam Định', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (37, 'Tỉnh Ninh Bình', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (38, 'Tỉnh Thanh Hóa', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (40, 'Tỉnh Nghệ An', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (42, 'Tỉnh Hà Tĩnh', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (44, 'Tỉnh Quảng Bình', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (45, 'Tỉnh Quảng Trị', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (46, 'Tỉnh Thừa Thiên Huế', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (48, 'Thành phố Đà Nẵng', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (49, 'Tỉnh Quảng Nam', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (51, 'Tỉnh Quảng Ngãi', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (52, 'Tỉnh Bình Định', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (54, 'Tỉnh Phú Yên', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (56, 'Tỉnh Khánh Hòa', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (58, 'Tỉnh Ninh Thuận', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (60, 'Tỉnh Bình Thuận', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (62, 'Tỉnh Kon Tum', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (64, 'Tỉnh Gia Lai', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (66, 'Tỉnh Đắk Lắk', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (67, 'Tỉnh Đắk Nông', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (68, 'Tỉnh Lâm Đồng', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (70, 'Tỉnh Bình Phước', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (72, 'Tỉnh Tây Ninh', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (74, 'Tỉnh Bình Dương', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (75, 'Tỉnh Đồng Nai', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (77, 'Tỉnh Bà Rịa - Vũng Tàu', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (79, 'Thành phố Hồ Chí Minh', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (80, 'Tỉnh Long An', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (82, 'Tỉnh Tiền Giang', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (83, 'Tỉnh Bến Tre', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (84, 'Tỉnh Trà Vinh', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (86, 'Tỉnh Vĩnh Long', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (87, 'Tỉnh Đồng Tháp', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (89, 'Tỉnh An Giang', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (91, 'Tỉnh Kiên Giang', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (92, 'Thành phố Cần Thơ', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (93, 'Tỉnh Hậu Giang', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (94, 'Tỉnh Sóc Trăng', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (95, 'Tỉnh Bạc Liêu', NULL);
INSERT INTO `province` (`id_province`, `str_province`, `id_status`) VALUES (96, 'Tỉnh Cà Mau', NULL);
